services:
  - type: web
    name: naresh-portfolio
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0